# mybatis配置
mybatis:
  mapper-locations: classpath:/mapper/*.xml

spring:
  datasource:
    url: jdbc:mysql://192.168.47.229:3306/mook?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    password: cr970312
    username: root
    driver-class-name: com.mysql.jdbc.Driver

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
        date-format: yyyy-MM-dd HH:mm:ss
JWT:
  secrect: qwertyuiopasdfghjklzxcvbnmqwerty
  expire: 6000000

server:
  port: 8888